install:
- choco install gradle -version 5.2.1
- set JAVA_HOME=C:\Program Files\Java\jdk12
- set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
- gradle -version

build_script:
- gradle assemble --no-daemon --info
- gradle updateSHAs --no-daemon --info

test_script:
- gradle check --no-daemon --info

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
