<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.htrucker</groupId>
        <artifactId>jmorphy2-parent</artifactId>
        <version>0.4.0</version>
    </parent>

    <artifactId>jmorphy2-solr</artifactId>
    <name>jmorphy2-solr</name>
    <description>Solr stemmer and tagger based on jmorphy2</description>

    <dependencies>
        <dependency>
            <groupId>org.apache.solr</groupId>
            <artifactId>solr-core</artifactId>
            <version>${solr.version}</version>
        </dependency>
        <dependency>
            <groupId>com.htrucker</groupId>
            <artifactId>jmorphy2-lucene</artifactId>
        </dependency>

        <dependency>
            <groupId>com.htrucker</groupId>
            <artifactId>jmorphy2-dicts-ru</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.htrucker</groupId>
            <artifactId>jmorphy2-core</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
